//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wypozycalnia2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Samochody
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Samochody()
        {
            this.Wypożyczalnia = new HashSet<Wypożyczalnia>();
            this.Wypożyczenia = new HashSet<Wypożyczenia>();
        }
    
        public int IdSamochodu { get; set; }
        public string MarkaSamochodu { get; set; }
        public string ModelSamochodu { get; set; }
        public Nullable<int> RokProduckji { get; set; }
        public int CenaZaDzien { get; set; }
        public bool Dostepnosc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wypożyczalnia> Wypożyczalnia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wypożyczenia> Wypożyczenia { get; set; }
    }
}
